---
title: "map_tag()"
resource_files:
- vft.csv
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    theme: united
    orientation: columns
    social: menu
    source_code: embed
    navbar:
    - align: right
      href: https://github.com/maurolepore
      icon: fa-user
      title: Mauro Lepore
---

```{r global, include=FALSE}
library(flexdashboard)
library(try)
library(dplyr)
library(ggplot2)
library(icon)
```

Upload a file, change key arguments of map_tag(), and preview the effect
=======================================================================

--- DATA {data-width=350}
-----------------------------------------------------------------------

```{r}
notice <- "Upload a .csv file (will show one quadrat only):"
fileInput("dataset", notice)
active_df <- reactive({
  req(input$dataset)
  readr::read_csv(input$dataset$datapath)
})
```

Example data set, after filtering a unique `PlotID`

```{r}
vft <- as_tibble(try::bci12vft_mini)
datex <- dplyr::filter(vft, PlotID == 1)

# This data set has two wrong names that need to be fixed before using map_tag()
first_quad <- unique(datex$QuadratName)[[1]]

vars <-  c("tag", "x", "y", "status", "quadratname", "censusid", "plotid")
datex1 <- datex[, tolower(names(datex)) %in% vars]

example_data <- datex1 %>% 
  dplyr::rename(qx = x, qy = y) %>% 
  dplyr::filter(QuadratName %in% first_quad) %>% 
  print(n = 3)
```

### Glimpse of uploaded data (showing only the first row) {data-height=35}

```{r}
renderPrint({
  rngx <- paste0(range(active_df()$qx), collapse = " ")
  rngy <- paste0(range(active_df()$qy), collapse = " ")
  cat("range qx: ", rngx, "\n", "range qy: ", rngy, "\n", "\n", sep = "")
  glimpse(active_df()[1, ])
})
```

--- ARGUMENTS {data-width=250}
-----------------------------------------------------------------------

`r icon::fa_question_circle()` [`map_tag()`](https://forestgeo.github.io/try/reference/map_tag.html)

```{r}
textInput("site", "site_name", "My site, 2017")

fluidRow(
  column(6, numericInput("xquad", "x_q", 20)),
  column(6, numericInput("xsubquad", "x_sq", 5))
)

fluidRow(
  column(6, numericInput("tagsize", "tag_size", 3)),
  column(6, numericInput("pointsize", "point_size", 1.5))
)

fluidRow(
  column(
    6, 
    sliderInput(
      "pointshape_alive", "point_shape (alive)", min = 1, max = 25, 19)
  ),
  column(
    6, 
    sliderInput(
      "pointshape_dead", "point_shape (dead)", min = 1, max = 25, 4)
  )
)
```

`r icon::fa_question_circle()` [`get_header()`](https://forestgeo.github.io/try/reference/get_header.html)

```{r}
textInput("line_1", "line1", pad(c("Checking: ", "Checked date: ")))
textInput("line_2", "line2", pad(c("Recording: "), total_width = 24))
textInput("line_3", "line3", pad(c("Measuring: ", "Measurement date: ")))
```



--- PLOT {data-width=350}
-----------------------------------------------------------------------

### Preview

```{r, fig.asp=1.15}
renderPlot({
  maps <- map_tag(
    active_df(), 
    x_q = input$xquad,
    x_sq = input$xsubquad,
    site_name = input$site,
    point_size = input$pointsize,
    point_shape = c(input$pointshape_alive, input$pointshape_dead),
    tag_size = input$tagsize,
    header = get_header(
      line1 = input$line_1,
      line2 = input$line_2,
      line3 = input$line_3
    )
  )
  maps[[1]]
})
```

