---
title: "Mapping quadrats of plot-lines 0-9"
output:
  rmarkdown::html_notebook:
    toc: true
    toc_depth: 6
    theme: united
---

```{r setup, include=FALSE}
set.seed(1014)
options(digits = 3)

knitr::opts_chunk$set(
  echo = TRUE,
  comment = "#>",
  collapse = TRUE,
  cache = TRUE,
  out.width = "98%", 
  fig.width = 12, 
  fig.asp = 0.75,
  fig.align = "center",
  fig.show = "hold"
)
```

> LINE number is the y-coordinate of the quadrat coordinates:  LINE “0” includes quadrats: 2400, 2300, 2200, to 0000

# Package

```{r}
library(fgeo.map)
library(dplyr)
```

# Data

```{r, eval=FALSE, include=FALSE}
path <- "C:/Users/dora/Downloads/sinharajamapdata/sinharajamapdata.txt"
vft <- readr::read_delim(path, delim = "\t")
vft
```

```{r}
# `sinharaja::sinh_vft_20180118` is a private dataset. Instead use your data.
vft <- sinharaja::sinh_vft_20180118
```

# CHeck how many maps R will let you print

```{r}
options("max.print")
old_opitons <- options()

options(max.print = 5000)
options("max.print")
```

# Suffix dead trees on the quadrat edge

```{r}
suffixed <- suffix_edge_tag(
  vft,
  .match = "dead",
  suffix = "_d",
  x_q = 20
)
# Confirm that it worked
dplyr::filter(suffixed, status == "dead", (qx > 20 | qy > 20))
```

# Map

```{r}
p <- map_tag(suffixed, title_quad = "Sinharaja, 2018.", move_edge = 0.5)
```

# Check the order of quadrats is correct

```{r}
names(p[1:100])
```

# Print pdf

```{r}
pdf("Sinharaja_2018_q2213.pdf", paper = "letter", height = 10.5, width = 8)
p
dev.off()
```

# Filter quadrats on lines 0-9

```{r}
library(stringr)

rows <- str_pad(0:9, width = 2, pad = "0")
rows
```

```{r}
rows_pattern <- paste0("^..", rows, "$")

vft$lines_0to9 <- str_detect(vft$quadratname, rows_pattern)
vft_ln_0to9 <- vft[vft$lines_0to9, ]

unique(vft_ln_0to9$quadratname)
```

# Map quadrats to confirm

```{r}
all_q <- sinharaja::sinh_vft
sel_q <- filter(all_q, QuadratName %in% unique(vft_ln_0to9$quadratname)) %>% 
  select(QuadratName, everything())
ggplot(all_q, aes(PX, PY)) +
  geom_text(data = sel_q, aes(label = QuadratName))
```

