---
title: "Find tag with the highest number per column"
subtitle: "For David"
author: "maurolepore@gmail.com"
date: "2017-11-05"
output:
  rmarkdown::html_document:
    toc: true
    toc_depth: 6
---


```{r setup, include=FALSE}
# > There is one chunk name that imbues special behaviour: setup. When you're in
# a notebook mode, the chunk named setup will be run automatically once, before
# any other code is run.
# --http://r4ds.had.co.nz/r-markdown.html#chunk-options



# Load packages (including data-packages) ----

library(ggplot2)
library(dplyr)



# Load un-packaged dependencies ----





# Figures ----

# > If you want to make sure the font size is consistent across all your
# figures, whenever you set out.width, you'll also need to adjust fig.width to
# maintain the same ratio with your default out.width. For example, if your
# default fig.width is 6 and out.width is 0.7, when you set out.width = "50%"
# you'll need to set fig.width to 4.3 (6 * 0.5 / 0.7).
# --http://r4ds.had.co.nz/

set.seed(1014)
options(digits = 3)

knitr::opts_chunk$set(
  echo = TRUE,
  comment = "#>",
  collapse = TRUE,
  cache = TRUE,
  out.width = "70%",
  fig.align = "center",
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold",
  rows.print = 3  # {mine}
)

options(dplyr.print_min = 10, dplyr.print_max = 10)

# customize ggplot

update_geom_defaults("point",
  list(shape = 21, colour = "black", size = 5, stroke = 1)
)
update_geom_defaults("text", list(size = 4.5))
```

### Setup

```{r}
library(dplyr)

add_subquadrat <- function(df, dim_x, dim_y, div_x, div_y) {
  # Simplify nested parentheses
  dim_x_mns.1 <- dim_x - 0.1
  dim_y_mns.1 <- dim_y - 0.1

  # Conditions
  is_odd_both <- df$qx >=  dim_x & df$qy >=  dim_y
  is_odd_x <- df$qx >=  dim_x
  is_odd_y <- df$qy >=  dim_y
  is_not_odd <- TRUE

  # Cases
  with_subquadrat <- dplyr::mutate(df,
    subquadrat = dplyr::case_when(
      is_odd_both ~ paste0(
        (1 + floor((dim_x_mns.1 - dim_x * floor(dim_x_mns.1 / dim_x)) / div_x)),
        (1 + floor((dim_y_mns.1- dim_y * floor(dim_y_mns.1/ dim_y)) / div_y))
      ),
      is_odd_x ~ paste0(
        (1 + floor((dim_x_mns.1 - dim_x * floor(dim_x_mns.1 / dim_x)) / div_x)),
        (1 + floor((df$qy - dim_y * floor(df$qy/ dim_y)) / div_y))
      ),
      is_odd_y ~ paste0(
        (1 + floor((df$qx - dim_x * floor(df$qx/ dim_x)) / div_x)),
        (1 + floor((dim_y_mns.1- dim_y * floor(dim_y_mns.1 / dim_y)) / div_y))
      ),
      is_not_odd ~ paste0(
        (1 + floor((df$qx - dim_x * floor(df$qx/ dim_x)) / div_x)),
        (1 + floor((df$qy - dim_y * floor(df$qy/ dim_y)) / div_y))
      )
    )
  )
  with_subquadrat
}
```

### Wrangle

```{r}
# Wrangle
vft <- ngelnyaki::ngelnyaki_vft_unid
names(vft) <- tolower(names(vft))
with_subquadrat <- add_subquadrat(vft, 20, 20, 5, 5)

all_tags_arranged <- with_subquadrat %>%
  # Extract column number from variable subquadrat
  mutate(column = stringr::str_extract(subquadrat, "^.")) %>%
  # Keep only relevant columns
  select(quadratname, subquadrat, column, tag) %>%
  group_by(quadratname, subquadrat, column) %>%
  arrange(desc(tag), .by_group = TRUE) %>%
  unique()
all_tags_arranged

max_tag_per_column_per_quadrat <- all_tags_arranged %>% top_n(1, tag)
max_tag_per_column_per_quadrat

readr::write_csv(
  max_tag_per_column_per_quadrat, "max_tag_per_column_per_quadrat.csv"
)
```

