---
title: "Labelling and mapping trees that spillover"
output:
  rmarkdown::html_notebook:
    toc: true
    toc_depth: 6
    theme: united
---

```{r setup, include=FALSE}
set.seed(1014)
options(digits = 3)

knitr::opts_chunk$set(
  echo = TRUE,
  comment = "#>",
  collapse = TRUE,
  cache = TRUE,
  out.width = "98%", 
  fig.width = 12, 
  fig.asp = 0.75,
  fig.align = "center",
  fig.show = "hold"
)
```

# Package

```{r}
library(fgeo.map)
```

# Data

```{r}
# `sinharaja::sinh_vft_20180118` is a private dataset. Instead use your data.
vft <- sinharaja::sinh_vft_20180118
```

# Suffix dead trees on the quadrat edge

```{r}
suffixed <- suffix_edge_tag(
  vft,
  .match = "dead",
  suffix = "_d",
  x_q = 20
)
# Confirm that it worked
dplyr::filter(suffixed, status == "dead", (qx > 20 | qy > 20))
```

# Map

```{r}
# Showing only one quadrat
vft_q0002 <- dplyr::filter(suffixed, quadratname == "0002")
p <- map_tag(vft_q0002)
# Showing only one of the four maps of the quadrat 0002
p[[3]]
```

# Print to .pdf

```{r}
# Printing all plots of `p` to .pdf, with parameters optimized for size letter
pdf("map.pdf", paper = "letter", height = 10.5, width = 8)
p
dev.off()
```

