---
title: "Comparing ggplot2 and fgeo.plot"
author: "Mauro Lepore"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, echo = FALSE, message=FALSE, warning=FALSE}
# hadley's settings
set.seed(1014)
options(digits = 3)

knitr::opts_chunk$set(
  echo = TRUE,  # {mine}
  comment = "#>",
  collapse = TRUE,
  # cache = TRUE,
  out.width = "100%",
  fig.align = "center",
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold",
  rows.print = 3  # {mine}
)
```

This article compares plots built with __fgeo.plot__ versus __ggplot2__. 

# Elevation

Data

```{r}
# https://forestgeo.github.io/fgeo.plot/
library(fgeo.plot)

elevation <- fgeo.data::luquillo_elevation
str(elevation)
# Pull elevation dataframe
elev <- elevation$col
```

Auto-plots with __fgeo.plot__.

```{r}
plot_elevation(elev)
```

```
# plot_elevation() also understands the elevation list, so this code outputs the same
plot_elevation(elevation)
```

```{r}
# You have a number of options you can tweak
plot_elevation(elev,
  # Or choose colors by code from http://bit.ly/2rJgQba
  low = "grey", high = "black", 
  # How many lines, and how thick
  bins = 20, contour_size = 0.5,
  # Hide elevation numbers from inside the plot
  add_elevation_labels = FALSE, 
  # Keep the "level" legend
  hide_color_legend = FALSE
)
```

More flexible maps with __ggplot2__. 

```{r}
# http://ggplot2.tidyverse.org/reference/
library(ggplot2)

ggplot(elev, aes(x = x, y = y, z = elev)) +
  geom_raster(aes(fill = elev)) +
  geom_contour(color = "white", bins = 20) +
  scale_fill_gradient(low = "grey", high = "black") +
  coord_equal() +
  theme_bw()
```

